dbt_hive_demo:
  outputs:
    dev_hive:
      type: hive
      schema: "{{ env_var('DBT_SCHEMA') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      auth_type: "{{ env_var('DBT_AUTH_TYPE') }}"
      host: "{{ env_var('DBT_HOST') }}"
  target: dev_hive
